language: c

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - bison
            - xsltproc
            - libfreetype6-dev
            - libgtk2.0-dev
            - libsdl-dev
            - libreadline-dev
    - os: osx
      install: brew update && brew bundle

script: ./configure && make all && make test
