language: c

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - bison
            - xsltproc
            - libfreetype6-dev
            - libgtk2.0-dev
            - libsdl-dev
            - libreadline-dev
    - os: osx
      env:
        - BREW_PACKAGES="bison freetype gtk+ sdl readline"
        - CONFIGURE_FLAGS="--bison /usr/local/opt/bison/bin/bison"

install:
  - if test -n "$BREW_PACKAGES"; then brew update ; brew install $BREW_PACKAGES ; fi

script: ./configure $CONFIGURE_FLAGS && make all && make test
